# pull official base image
FROM python:3.9.5-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements_worker.txt .
RUN pip install -r requirements_worker.txt

RUN pip install watchdog
RUN pip install pyyaml

# copy project
COPY . .
