version: '3.6'

# networks:
#   airflow:

services:
  service:
    build:
      context: .
      # dockerfile: Dockerfile
      target: service
    ports:
      - "80:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      # - ./src:/usr/src
      - ./src:/root/app/site-packages
      - file-storage:/root/app/store
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    # networks:
    #   - airflow

  worker:
    build: ./src/openapi_server/worker
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./src/openapi_server/worker:/usr/src/app
      # - ./src/openapi_server/worker:/root/app/site-packages/worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - service
      - redis

  redis:
    image: redis:6-alpine

# dashboard:
#   build: ./project
#   command:  flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
#   ports:
#     - 5556:5555
#   environment:
#     - CELERY_BROKER_URL=redis://redis:6379/0
#     - CELERY_RESULT_BACKEND=redis://redis:6379/0
#   depends_on:
#     - web
#     - redis
#     - worker

volumes:
    file-storage:

