version: '3.6'

networks:
  airflow:

services:
  service:
    build:
      context: .
      # dockerfile: Dockerfile
      target: service
    ports:
      - "80:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      # - ./src:/usr/src
      - ./src:/root/app/site-packages
    networks:
      - airflow
