# coding: utf-8

"""
    Swagger Petstore

    SberZvuk API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Swagger Petstore",
    description="SberZvuk API",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
