# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class FoundVideoFragment(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FoundVideoFragment - a model defined in OpenAPI

        time_start: The time_start of this FoundVideoFragment [Optional].
        time_end: The time_end of this FoundVideoFragment [Optional].
        corner_1: The corner_1 of this FoundVideoFragment [Optional].
        corner_2: The corner_2 of this FoundVideoFragment [Optional].
    """

    time_start: Optional[float] = None
    time_end: Optional[float] = None
    corner_1: Optional[List[float]] = None
    corner_2: Optional[List[float]] = None

FoundVideoFragment.update_forward_refs()
