# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class FoundAudioFragment(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FoundAudioFragment - a model defined in OpenAPI

        time_start: The time_start of this FoundAudioFragment [Optional].
        time_end: The time_end of this FoundAudioFragment [Optional].
    """

    time_start: Optional[float] = None
    time_end: Optional[float] = None

FoundAudioFragment.update_forward_refs()
