# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.audio_result import AudioResult
from openapi_server.models.video_result import VideoResult


class RecognizeResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RecognizeResponse - a model defined in OpenAPI

        code: The code of this RecognizeResponse [Optional].
        status: The status of this RecognizeResponse [Optional].
        message: The message of this RecognizeResponse [Optional].
        audio_result: The audio_result of this RecognizeResponse [Optional].
        video_result: The video_result of this RecognizeResponse [Optional].
    """

    code: Optional[str] = None
    status: Optional[str] = None
    message: Optional[str] = None
    audio_result: Optional[AudioResult] = None
    video_result: Optional[VideoResult] = None

RecognizeResponse.update_forward_refs()
